version: '3.4'
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=candle
      - MYSQL_USER=candle
      - MYSQL_PASSWORD=candle
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=True
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://candle:candle@db/candle
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app/
    depends_on:
      - db

volumes:
  mysql_data:
